// <auto-generated />
namespace WaiterManagement.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Zmianywencjachlogowania : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Zmianywencjachlogowania));
        
        string IMigrationMetadata.Id
        {
            get { return "201511162326220_Zmiany w encjach logowania"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
